// <auto-generated />
using System;
using BD1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BD1.Migrations
{
    [DbContext(typeof(BD1Context))]
    [Migration("20201024104151_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiBi.Models.Avtomobili", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cena_avto")
                        .HasColumnType("int");

                    b.Property<int>("Cena_dlya_prokata")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_poslednego_TO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("God_vipyska")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nomer_dvigatelya")
                        .HasColumnType("int");

                    b.Property<int>("Nomer_kyzova")
                        .HasColumnType("int");

                    b.Property<string>("Otmetka_o_vozraste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Probeg")
                        .HasColumnType("int");

                    b.Property<int>("Registr_nomer")
                        .HasColumnType("int");

                    b.Property<string>("Spec_otmetki")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Avtomobili");
                });

            modelBuilder.Entity("DiBi.Models.Marki_avtomobiley", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AvtomobiliID")
                        .HasColumnType("bigint");

                    b.Property<string>("Naimenovanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opisanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tech_harakteristiki")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AvtomobiliID");

                    b.ToTable("Marki_avtomobiley");
                });

            modelBuilder.Entity("DiBi.Models.Prokat", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AvtomobiliID")
                        .HasColumnType("bigint");

                    b.Property<int>("Cena_prokata")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_vidachi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_vozvrata")
                        .HasColumnType("datetime2");

                    b.Property<string>("Otmetka_ob_oplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Srok_prokata")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AvtomobiliID");

                    b.ToTable("Prokat");
                });

            modelBuilder.Entity("DiBi.Models.Marki_avtomobiley", b =>
                {
                    b.HasOne("DiBi.Models.Avtomobili", null)
                        .WithMany("Kod_marki")
                        .HasForeignKey("AvtomobiliID");
                });

            modelBuilder.Entity("DiBi.Models.Prokat", b =>
                {
                    b.HasOne("DiBi.Models.Avtomobili", null)
                        .WithMany("Kod_prokata")
                        .HasForeignKey("AvtomobiliID");
                });
#pragma warning restore 612, 618
        }
    }
}
